{{- if and (eq .Values.contracts.source "configmap") .Values.contracts.configmap.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tauto.fullname" . }}-contracts
  labels:
    {{- include "tauto.labels" . | nindent 4 }}
data:
  {{- range $filename, $content := .Values.contracts.configmap.files }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
