{{- if and (eq .Values.contracts.source "pvc") (not .Values.contracts.pvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tauto.fullname" . }}
  labels:
    {{- include "tauto.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.contracts.pvc.accessMode }}
  storageClassName: {{ .Values.contracts.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.contracts.pvc.size }}
{{- end }}
