kind: DataContract
apiVersion: v3.1.0
id: inventory-reservation-state-contract
status: active
schema:
  - name: InventoryReservation
    physicalName: inventory_reservations
    properties:
      - name: reservationStatus
        physicalName: reservation_status
        logicalType: string
        quality:
          - metric: invalidValues
            arguments:
              validValues: [Requested, Held, Consumed, Released]
