kind: DataContract
apiVersion: v3.1.0
id: shipment-state-contract
status: active
schema:
  - name: Shipment
    physicalName: shipments
    properties:
      - name: shipmentStatus
        physicalName: shipment_status
        logicalType: string
        quality:
          - metric: invalidValues
            arguments:
              validValues: [Created, LabelPrinted, Picked, InTransit, Delivered]
