from pydantic import BaseModel, ConfigDict, Field

from tauto_contract_ir.models import ContractIR, ContractSet


class LeanWorkspaceFile(BaseModel):
    model_config = ConfigDict(frozen=True)

    path: str
    content: str


class LeanWorkspace(BaseModel):
    model_config = ConfigDict(frozen=True)

    files: list[LeanWorkspaceFile] = Field(default_factory=list)


def generate_lean_workspace(contract_set: ContractSet) -> LeanWorkspace:
    contract_files = [_contract_file(c) for c in contract_set.contracts]
    main_file = _main_module_file(contract_set)
    lakefile = _lakefile()
    return LeanWorkspace(files=[lakefile, main_file, *contract_files])


def _lakefile() -> LeanWorkspaceFile:
    content = """\
-- Auto-generated by Tauto. Do not edit manually.
name = "TautoContracts"
version = "0.1.0"

[[lean_lib]]
name = "TautoContracts"
"""
    return LeanWorkspaceFile(path="lakefile.toml", content=content)


def _main_module_file(contract_set: ContractSet) -> LeanWorkspaceFile:
    imports = "\n".join(
        f"import contracts.{_module_name(c)}" for c in contract_set.contracts
    )
    content = f"-- Auto-generated by Tauto. Do not edit manually.\n{imports}\n"
    return LeanWorkspaceFile(path="TautoContracts.lean", content=content)


def _contract_file(contract: ContractIR) -> LeanWorkspaceFile:
    module = _module_name(contract)
    content = _render_contract(contract)
    return LeanWorkspaceFile(path=f"contracts/{module}.lean", content=content)


def _module_name(contract: ContractIR) -> str:
    return contract.case.replace(" ", "")


def _render_contract(contract: ContractIR) -> str:
    lines: list[str] = [
        "-- Auto-generated by Tauto. Do not edit manually.",
        f"-- Contract: {contract.case}",
        f"-- Entity: {contract.entity}",
        f"-- Operation: {contract.operation}",
        "",
        f"namespace Tauto.Contracts.{_module_name(contract)}",
        "",
    ]

    if contract.requires:
        lines += _theorem_stub("requires", contract.requires, contract)

    if contract.ensures:
        lines += _theorem_stub("ensures", contract.ensures, contract)

    if contract.forbidden:
        lines.append("-- Forbidden operations:")
        for f in contract.forbidden:
            args = ", ".join(_render_expr(a) for a in f.args)
            lines.append(f"--   {f.operation}({args})")
        lines.append("")

    if contract.preserves:
        lines.append("-- Preserved invariants:")
        for inv in contract.preserves:
            lines.append(f"--   {inv}")
        lines.append("")

    lines += [f"end Tauto.Contracts.{_module_name(contract)}", ""]
    return "\n".join(lines)


def _theorem_stub(kind: str, conditions: list, contract: ContractIR) -> list[str]:
    name = f"{_camel_case(contract.operation)}_{kind}"
    lines = [
        f"theorem {name} :",
        "  -- TODO: formalize the following conditions",
    ]
    for cond in conditions:
        left = _render_expr(cond.left)
        right = _render_expr(cond.right)
        lines.append(f"  --   {left} {cond.operator} {right}")
    lines += ["  True := by", "  sorry", ""]
    return lines


def _render_expr(expr) -> str:
    return str(expr.value)


def _camel_case(s: str) -> str:
    return s[:1].lower() + s[1:] if s else s
