import re

from pydantic import BaseModel, ConfigDict, Field

from tauto_contract_ir.models import Condition, ContractIR, ContractSet, Expression

_NON_IDENT_RE = re.compile(r"[^A-Za-z0-9]")

__all__ = [
    "LeanWorkspace",
    "LeanWorkspaceFile",
    "generate_lean_workspace",
]


class LeanWorkspaceFile(BaseModel):
    model_config = ConfigDict(frozen=True)

    path: str
    content: str


class LeanWorkspace(BaseModel):
    model_config = ConfigDict(frozen=True)

    files: list[LeanWorkspaceFile] = Field(default_factory=list)


def generate_lean_workspace(contract_set: ContractSet) -> LeanWorkspace:
    module_names = _assign_module_names(contract_set.contracts)
    contract_files = [
        _contract_file(c, module_names[i]) for i, c in enumerate(contract_set.contracts)
    ]
    main_file = _main_module_file(module_names)
    lakefile = _lakefile()
    return LeanWorkspace(files=[lakefile, main_file, *contract_files])


def _assign_module_names(contracts: list[ContractIR]) -> list[str]:
    seen: dict[str, int] = {}
    names: list[str] = []
    for c in contracts:
        base = _lean_ident(c.case)
        count = seen.get(base, 0)
        seen[base] = count + 1
        names.append(base if count == 0 else f"{base}_{count}")
    return names


def _lean_ident(s: str) -> str:
    cleaned = _NON_IDENT_RE.sub("", s.replace(" ", ""))
    if not cleaned:
        return "Contract"
    if cleaned[0].isdigit():
        cleaned = "C" + cleaned
    return cleaned


def _lakefile() -> LeanWorkspaceFile:
    content = """\
# Auto-generated by Tauto. Do not edit manually.
name = "TautoContracts"
version = "0.1.0"

[[lean_lib]]
name = "TautoContracts"
"""
    return LeanWorkspaceFile(path="lakefile.toml", content=content)


def _main_module_file(module_names: list[str]) -> LeanWorkspaceFile:
    imports = "\n".join(f"import contracts.{name}" for name in module_names)
    content = f"-- Auto-generated by Tauto. Do not edit manually.\n{imports}\n"
    return LeanWorkspaceFile(path="TautoContracts.lean", content=content)


def _contract_file(contract: ContractIR, module_name: str) -> LeanWorkspaceFile:
    content = _render_contract(contract, module_name)
    return LeanWorkspaceFile(path=f"contracts/{module_name}.lean", content=content)


def _render_contract(contract: ContractIR, module_name: str) -> str:
    op_ident = _lean_ident(contract.operation)
    lines: list[str] = [
        "-- Auto-generated by Tauto. Do not edit manually.",
        f"-- Contract: {contract.case}",
        f"-- Entity: {contract.entity}",
        f"-- Operation: {contract.operation}",
        "",
        f"namespace Tauto.Contracts.{module_name}",
        "",
    ]

    if contract.requires:
        lines += _theorem_stub("requires", contract.requires, op_ident)

    if contract.ensures:
        lines += _theorem_stub("ensures", contract.ensures, op_ident)

    if contract.forbidden:
        lines.append("-- Forbidden operations:")
        for f in contract.forbidden:
            args = ", ".join(_render_expr(a) for a in f.args)
            lines.append(f"--   {f.operation}({args})")
        lines.append("")

    if contract.preserves:
        lines.append("-- Preserved invariants:")
        for inv in contract.preserves:
            lines.append(f"--   {inv}")
        lines.append("")

    lines += [f"end Tauto.Contracts.{module_name}", ""]
    return "\n".join(lines)


def _theorem_stub(kind: str, conditions: list[Condition], op_ident: str) -> list[str]:
    name = f"{op_ident}_{kind}"
    lines = [
        f"theorem {name} :",
        "  -- TODO: formalize the following conditions",
    ]
    for cond in conditions:
        left = _render_expr(cond.left)
        right = _render_expr(cond.right)
        lines.append(f"  --   {left} {cond.operator} {right}")
    lines += ["  True := by", "  sorry", ""]
    return lines


def _render_expr(expr: Expression) -> str:
    return str(expr.value)
